# This file is Free Software under the MIT License
# without warranty, see README.md and LICENSES/MIT.txt for details.
#
# SPDX-License-Identifier: MIT
#
# SPDX-FileCopyrightText: 2023 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2023 Intevation GmbH <https://intevation.de>
name: Integrationtest

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: "20.X"

      - name: "Install Deps"
        run: npm install

      - name: "Install playwright"
        run: npx playwright install

      - name: "Integration test"
        run: npm run test:integration
